spring.application.name=api-gateway

server.port=8080

# =========================================================
# CATALOG SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[0].id=catalog-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://catalog-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/cakes/**

# =========================================================
# ORDER SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://order-service:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/orders/**

# =========================================================
# RATING SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[2].id=rating-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://rating-service:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/ratings/**

# =========================================================
# NOTIFICATION SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[3].id=notification-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://notification-service:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/notifications/**

# =========================================================
# GLOBAL CORS
# =========================================================

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://127.0.0.1:5500,http://localhost:5500

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=false

# =========================================================
# REMOVE DUPLICATE CORS RESPONSE HEADERS
# =========================================================

spring.cloud.gateway.server.webflux.routes[0].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
spring.cloud.gateway.server.webflux.routes[1].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
spring.cloud.gateway.server.webflux.routes[2].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
spring.cloud.gateway.server.webflux.routes[3].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin