apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: localhost:5000/cake-delight-rating-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://host.docker.internal:3306/cake_delight_rating"

            - name: root
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username

            - name: root
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  selector:
    app: rating-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP